pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "MAVEN_HOME"
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/robinarehen/multi-modules'
            }
        }
        stage('Build') {
            steps {
                sh "mvn -Dmaven.test.failure.ignore=true clean package -f micro-product/pom.xml"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -f micro-product/pom.xml"
            }
        }
        stage('Sonar') {
            steps {
                sh "mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=545539121b7b4bcf97cf8aea6153cd81cc4ffaf3 -f micro-product/pom.xml"
            }
        }
        stage('Deploy') {
            steps {
                sh "mvn spring-boot:run -f micro-product/pom.xml"
            }
        }
    }
}
