pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "MAVEN_HOME"
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/robinarehen/multi-modules'
            }
        }
        stage('Build') {
            steps {
                // -f: permite especificar el pom.xml que se debe ejecutar
                // para cuando una carpeta raíz contiene varios proyectos o módulos
                sh "mvn -DskipTests clean package -f micro-product/pom.xml"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -f micro-product/pom.xml"
            }
        }
        stage('Sonar') {
            steps {
                sh "mvn sonar:sonar -Pcoverage -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=token -f micro-product/pom.xml"
            }
        }
        stage('Deploy') {
            steps {
                sh "mvn spring-boot:run -f micro-product/pom.xml"
            }
        }
    }
}
